# 데이터 핸들링 (with pandas)

## 1. 데이터 생성
### 1.1 pandas Series

In [2]:
import pandas as pd
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values

array([ 4,  7, -5,  3])

In [4]:
obj2 = pd.Series([4,7,-5,3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

### 1.2 pandas DataFrame

In [24]:
columns = ['name', 'age', 'gender', 'job']

user1 = pd.DataFrame([['alice', 19, "F", "student"], 
                      ['john', 26, "M", "student"]], 
                     columns=columns)
user1

name  age gender      job
0  alice   19      F  student
1   john   26      M  student

In [43]:
user2 = pd.DataFrame([['eric', 22, "M", "student"], 
                      ['paul', 58, "F", "manager"]], 
                     columns=columns)
user2

name  age gender      job
0  eric   22      M  student
1  paul   58      F  manager

In [25]:
user3 = pd.DataFrame(dict(name=['peter', 'julie'], 
                          age=[33, 44], 
                          gender=['M', 'F'], 
                          job=['engineer', 'scientist']))
user3

name  age gender        job
0  peter   33      M   engineer
1  julie   44      F  scientist

## 2. 데이터 합치기
### 2.1 데이터 합치기 : Combine

In [8]:
# Combining DataFrames
user1.append(user2)

name  age gender      job
0  alice   19      F  student
1   john   26      M  student
0   eric   22      M  student
1   paul   58      F  manager

In [16]:
users = pd.concat([user1, user2, user3])
users

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
0   eric   22      M    student
1   paul   58      F    manager
0  peter   33      M   engineer
1  julie   44      F  scientist

### 2.2 데이터 합치기 : Join

#### default : inner join
    - inner join     pd.merge(df1, df2)
    - outer join     pd.merge(df1, df2, how = 'outer')
    - left join      pd.merge(df1, df2, how = 'left')
    - right join     pd.merge(df1, df2, how = 'right')

In [17]:
# Join DataFrame
user4 = pd.DataFrame(dict(name=['alice', 'john', 'eric', 'julie'], 
                          height=[165, 180, 175, 171]))
user4

name  height
0  alice     165
1   john     180
2   eric     175
3  julie     171

In [19]:
# Use union of keys from both frames
users2 = pd.merge(users, user4, on="name")
users2

name  age gender        job  height
0  alice   19      F    student     165
1   john   26      M    student     180
2   eric   22      M    student     175
3  julie   44      F  scientist     171

#### how 옵션을 통해 외부조인을 할 수 있다.

In [20]:
users3 = pd.merge(users, user4, on="name", how='outer')
users3

name  age gender        job  height
0  alice   19      F    student   165.0
1   john   26      M    student   180.0
2   eric   22      M    student   175.0
3   paul   58      F    manager     NaN
4  peter   33      M   engineer     NaN
5  julie   44      F  scientist   171.0

#### left_on, right_on을 이용하여key로 사용할 칼럼명을 각각 지정할 수 있다.

In [21]:
pd.merge(users, user4, left_on = 'name', right_on = 'name')

name  age gender        job  height
0  alice   19      F    student     165
1   john   26      M    student     180
2   eric   22      M    student     175
3  julie   44      F  scientist     171

### 2.3 데이터 합치기 : numpy 이용

In [27]:
import numpy as np

arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
np.vstack([arr,arr])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
np.hstack([arr,arr])

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [28]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

## 4. 컬럼 선택(Column selection)

In [44]:
users

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
0   eric   22      M    student
1   paul   58      F    manager
0  peter   33      M   engineer
1  julie   44      F  scientist

In [32]:
users['gender'] # select one column

0    F
1    M
0    M
1    F
0    M
1    F
Name: gender, dtype: object

In [33]:
users.gender # select one column using the DataFrame

0    F
1    M
0    M
1    F
0    M
1    F
Name: gender, dtype: object

In [34]:
# select multiple columns
users[['age', 'gender']] # select two columns

age gender
0   19      F
1   26      M
0   22      M
1   58      F
0   33      M
1   44      F

In [66]:
users.iloc[:,1:3]

age gender
0   19      F
1   26      M
0   22      M
1   58      F
0   33      M
1   44      F

In [67]:
users.loc[:,['age','gender']]

age gender
0   19      F
1   26      M
0   22      M
1   58      F
0   33      M
1   44      F

## 5. 로우 선택(Row selection)

In [57]:
df = users.copy()
df.iloc[0] # first row

name        alice
age            19
gender          F
job       student
Name: 0, dtype: object

In [86]:
print(df.iloc[0, 0]) # first item of first row

alice


In [53]:
df.iloc[0, 1] = 55
print(df)

    name  age gender        job     1
0  alice   55      F    student  55.0
1   john   26      M    student   NaN
0   eric   22      M    student  55.0
1   paul   58      F    manager   NaN
0  peter   33      M   engineer  55.0
1  julie   44      F  scientist   NaN


In [54]:
df.loc[0, 1] = 55
print(df)

    name  age gender        job     1
0  alice   55      F    student  55.0
1   john   26      M    student   NaN
0   eric   22      M    student  55.0
1   paul   58      F    manager   NaN
0  peter   33      M   engineer  55.0
1  julie   44      F  scientist   NaN


In [49]:
print(df.iloc[0]) 

name        alice
age            19
gender          F
job       student
Name: 0, dtype: object


In [56]:
df.loc[0]

name  age gender       job     1
0  alice   55      F   student  55.0
0   eric   22      M   student  55.0
0  peter   33      M  engineer  55.0

In [55]:
print(df.loc[0, "age"]) 

0    55
0    22
0    33
Name: age, dtype: int64


In [90]:
df.loc[0, "age"] = 19
print(df)

    name  age gender        job  height
0  alice   19      F    student   165.0
1   john   26      M    student   180.0
2   eric   22      M    student   175.0
3   paul   58      F    manager     NaN
4  peter   33      M   engineer     NaN
5  julie   44      F  scientist   171.0


## 6. 필터링(Filtering)

In [35]:
# simple logical filtering
users[users.age < 20]       # only show users with age < 20

name  age gender      job
0  alice   19      F  student

In [37]:
# Advanced logical filtering
users[users.age < 20][['age', 'job']] # select multiple columns

age      job
0   19  student

In [38]:
users[(users.age > 20) & (users.gender == 'M')] # use multiple conditions

name  age gender       job
1   john   26      M   student
0   eric   22      M   student
0  peter   33      M  engineer

In [39]:
users[users.job.isin(['student', 'engineer'])] # filter specific values

name  age gender       job
0  alice   19      F   student
1   john   26      M   student
0   eric   22      M   student
0  peter   33      M  engineer

## 7. 정렬(sorting)

In [68]:
# sort rows by a specific column
df = users.copy()
df.sort_values(by='age') 

name  age gender        job
0  alice   19      F    student
0   eric   22      M    student
1   john   26      M    student
0  peter   33      M   engineer
1  julie   44      F  scientist
1   paul   58      F    manager

In [69]:
# use descending order instead
df.sort_values(by='age', ascending=False) 

name  age gender        job
1   paul   58      F    manager
1  julie   44      F  scientist
0  peter   33      M   engineer
1   john   26      M    student
0   eric   22      M    student
0  alice   19      F    student

In [70]:
# sort by multiple columns
df.sort_values(by=['job', 'age']) 

name  age gender        job
0  peter   33      M   engineer
1   paul   58      F    manager
1  julie   44      F  scientist
0  alice   19      F    student
0   eric   22      M    student
1   john   26      M    student